USE AutoPartsDB;
GO
CREATE TABLE Images (
    Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
    AutoPartId INT CONSTRAINT FK_AutoPartId FOREIGN KEY REFERENCES AutoParts(Id),
    [Image] VARBINARY(MAX) NOT NULL
);